export const director = ['co522@humboldt.edu', 'cyril.oberlander@humboldt.edu']
export const management = ['ab632@humboldt.edu']
export const modeler = ['htp27@humboldt.edu']
export const botanist = ['kll85@humboldt.edu']
export const admin = [...management, ...director, ...modeler, ...botanist,]